### ISSUE TITLE
Introduce CI, CD using github action

### ISSUE THREAD

**Issue by seopbo** [lassl/lassl#21]
# TODO
github action을 이용하여 `isort`, `black` formatting을 강제하기

**Comment by dhkim0225** [comment]
도움이 되실 수 있을 것 같아, 자주 사용하는 config 공유 드립니다.
```
name: CI

on: pull_request

jobs:
  black:
    runs-on: [self-hosted, cpu]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install black
      run: pip install --upgrade black==21.9b0
    - name: Run black
      run: black --check . --extend-exclude crafts_pytorch/third_party

  isort:
    runs-on: [self-hosted, cpu]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install isort
      run: pip install --upgrade isort==5.9.3
    - name: Run isort
      working-directory: ./crafts_pytorch
      run: isort --profile black --check --skip third_party .

  mypy:
    runs-on: [self-hosted, cpu]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install mypy
        run: pip install --upgrade mypy==0.910 types-requests==2.25.9 types-ujson==0.1.1
      - name: Run mypy
        run: mypy --ignore-missing-imports . --exclude third_party

  pylint:
    runs-on: [self-hosted, cpu]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install pylint
        run: pip install --upgrade pylint==2.11.1
      - name: Run pylint
        run: pylint *

  pytest:
    runs-on: [self-hosted, gpu]
    container:
      image: dhkim0225/dl:cu102_pytorch1.9.0_py39_21.08
      volumes:
        - /mnt/cmlssd004:/mnt/cmlssd004
        - /mnt/ocr-nfsx1:/mnt/ocr-nfsx1
        - /home1/irteamsu/nsml-local:/nsml-local
      options: --gpus all --memory=64G --shm-size=32G
    steps:
    - name: Update GIT for submodule checkout
      run: add-apt-repository ppa:git-core/ppa -y && apt update && apt install --upgrade -y git
    - name: Checkout with submodule
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_USER_PAT }}
        submodules: recursive
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install Local NSML
      run: pip install /nsml-local
    - name: Install requirements
      run: pip install -r ./crafts_pytorch/requirements.txt
    - name: Install other stuffs
      run: pip install munch pynubes --trusted-host pypi.clova.ai --index-url http://pypi.clova.ai
    - name: Run pytest
      working-directory: ./crafts_pytorch
      run: pytest --ignore=third_party
```
