### ISSUE TITLE
KoRobertaSmall training

### ISSUE THREAD

**Issue by seopbo** [lassl/lassl#32]
# TODO
## Training tokenizer
```bash
poetry run python3 train_tokenizer.py --corpora_dir corpora \
--corpus_type sent_text \
--model_type roberta \
--vocab_size 51200 \
--min_frequency 2
```

## Serializing corpora
```bash
poetry run python3 serialize_corpora.py --model_type roberta \
--tokenizer_dir tokenizers/roberta \
--corpora_dir corpora \
--corpus_type sent_text \
--max_length 512 \
--num_proc 96 \
--batch_size 1000 \
--writer_batch_size 1000
```

ref: 
- https://github.com/huggingface/blog/blob/master/notebooks/13_pytorch_xla.ipynb

**Comment by bzantium** [comment]
## Pretrain language model
```yaml
# configs/roberta-small.yaml 수정
model:
  attention_probs_dropout_prob: 0.1
  bos_token_id: 0
  eos_token_id: 2
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  hidden_size: 256
  initializer_range: 0.02
  intermediate_size: 1024
  layer_norm_eps: 1e-05
  max_position_embeddings: 512
  model_type: "roberta"
  num_attention_heads: 4
  num_hidden_layers: 12
  pad_token_id: 1
  type_vocab_size: 1
  vocab_size: 51200
data:
  data_dir: "datasets/roberta"
  test_size: 0.0 # If you set this argument, arguments must be floating type. (e.g. 0.01)
collator:
  mlm_probability: 0.15
training:
  output_dir: "checkpoints/roberta"
  overwrite_output_dir: True # 수정
  do_train: True
  do_eval: False
  per_device_train_batch_size: 64 # 수정
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  max_steps: 1000000
  lr_scheduler_type: "linear"
  warmup_steps: 10000
  logging_strategy: "steps"
  logging_steps: 500
  evaluation_strategy: "no"
  eval_steps: 0
  save_strategy: "steps"
  save_steps: 10000
  save_total_limit: 5
  seed: 42
  fp16: False
  tpu_num_cores: 8 # 수정
  sharded_ddp: False
  deepspeed:
  gradient_checkpointing: False
```
```
# Pytorch TPU 주소 연동
export XRT_TPU_CONFIG="localservice;0;localhost:51011"
```
```bash
# 실행 명령어
python3 xla_spawn.py --num_cores 8 pretrain_language_model.py --config_path configs/roberta-base.yaml
```
